<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Example 2</title>
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css')}}">
    <style>
    .cabecera{
    text-align: center;
}
        tr {
    page-break-inside: avoid;
}
    </style>
  </head>
  <body>

    
      <div class="cabecera">
        <h1>Inventario General</h1>
        <p>Aula de Innovacion Pedogica</p>
      </div>
      <div>
      <table class="table table-bordered">
        <thead>
          <tr>
                
                <th>Codigo Patrimonial</th>
                <th>Descripcion del Bien</th>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Serial</th>
                <th>Color</th>
                <th>Dimension</th>
                <th>Estado</th>
                <th>Fecha de ingreso</th>
                <th>Pais de Origen</th>
                <th>Ubicacion</th>
                <th>Responsable</th>
                
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>2</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>3</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>4</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>5</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>6</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>7</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>8</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>9</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>10</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>11</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>12</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>13</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>14</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>15</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>16</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>17</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>18</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>19</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>20</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>21</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>22</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>23</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>24</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>25</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>26</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>27</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>28</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>29</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>30</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
            <tr>
                <td>31</td>
                <td>4</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>5</td>
                <td>fv</td>
                <td>7</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
                <td>d</td>
            </tr>
        </tbody>
      </table>
      </div>
  </body>
</html>